# AI Capabilities Atlas Funding Options
# Support the development of this open source AI tools directory

# Custom funding options for international donations
custom: [
  "mailto:princerunor@gmail.com?subject=AI%20Atlas%20Sponsorship&body=Hello%20Prince,%20I%20would%20like%20to%20support%20your%20AI%20Capabilities%20Atlas%20project.",
  "https://www.blockchain.com/btc/address/1Lrf92rUaecFkGVcmfduxRFELCf7LFo2c6",
  "https://etherscan.io/address/0x3313fc244467f8ac35658d13195ad076c5a24d54"
]

# Cryptocurrency Donation Addresses:
# Bitcoin (BTC): 1Lrf92rUaecFkGVcmfduxRFELCf7LFo2c6
# Ethereum (ETH): 0x3313fc244467f8ac35658d13195ad076c5a24d54  
# USDT (Solana): 7aaQt3Pwg7HPos9KBVSwWz13YjyZwS95apW5K8QkNbF5

# Professional Wire Transfer (via Geegpay):
# Account Holder: Prince Oghenerunor Omakpokpose
# Bank: Wells Fargo
# Account: 40630239770785636
# Routing: 121000248
# Swift: WFBIUS6SXXX
